from __future__ import annotations

import json
import shutil
from collections import Counter
from pathlib import Path
from typing import Any

from .preflop_context import build_preflop_context


STREET_ORDER = ("preflop", "flop", "turn", "river")


def build_state_review(
    *,
    events_path: Path,
    output_dir: Path,
    limit: int = 8,
    include_watch: bool = False,
) -> dict[str, Any]:
    """Create a screenshot-backed review report from saved screen-CV events.

    The report intentionally treats positions, bets, and buttons as CV
    observations. It does not reuse a historical gto_advice payload, because
    that payload can have been generated by an older inference policy.
    """

    events_path = Path(events_path)
    if not events_path.is_file():
        raise FileNotFoundError(f"events JSONL not found: {events_path}")
    if limit < 1:
        raise ValueError("limit must be at least 1")

    events, stats = load_reviewable_events(events_path, include_watch=include_watch)
    selected = select_diverse_events(events, limit=limit)
    output_dir = Path(output_dir)
    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    cases: list[dict[str, Any]] = []
    for number, event in enumerate(selected, start=1):
        image_path = copy_case_image(event, images_dir, number)
        case = build_case(event, number=number, image_path=image_path)
        cases.append(case)

    report_path = output_dir / "state_review.md"
    manifest_path = output_dir / "state_review_manifest.json"
    report_path.write_text(render_markdown(events_path, stats, cases), encoding="utf-8")
    manifest_path.write_text(
        json.dumps(
            {
                "ok": True,
                "events_path": str(events_path),
                "stats": stats,
                "cases": cases,
                "report_path": str(report_path),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return {
        "ok": True,
        "events_path": str(events_path),
        "output_dir": str(output_dir),
        "report_path": str(report_path),
        "manifest_path": str(manifest_path),
        "stats": stats,
        "cases": cases,
    }


def load_reviewable_events(events_path: Path, *, include_watch: bool) -> tuple[list[dict[str, Any]], dict[str, int]]:
    stats: Counter[str] = Counter()
    candidates: list[dict[str, Any]] = []
    with events_path.open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, start=1):
            if not line.strip():
                continue
            stats["lines"] += 1
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                stats["invalid_json"] += 1
                continue
            if not event.get("ok"):
                stats["cv_errors"] += 1
                continue
            stats["ok_events"] += 1
            hero_turn = as_dict(event.get("hero_turn"))
            if hero_turn.get("is_turn"):
                stats["hero_turn_events"] += 1
            elif not include_watch:
                continue
            hero = as_dict(event.get("hero"))
            table = as_dict(event.get("table"))
            street = str(table.get("street") or "").lower()
            if street not in STREET_ORDER:
                stats["invalid_street"] += 1
                continue
            cards = complete_cards(hero.get("cards"), expected=2)
            board = complete_board(table.get("board"), street)
            if not cards or not board:
                stats["incomplete_cards"] += 1
                continue
            source_image = resolve_source_image(event, events_path)
            if source_image is None:
                stats["missing_source_image"] += 1
                continue
            stats["image_backed_candidates"] += 1
            event["_review_line"] = line_number
            event["_review_source_image"] = str(source_image)
            candidates.append(event)

    stats["eligible_candidates"] = len(candidates)
    return candidates, dict(sorted(stats.items()))


def select_diverse_events(events: list[dict[str, Any]], *, limit: int) -> list[dict[str, Any]]:
    ranked = sorted(events, key=review_sort_key, reverse=True)
    selected: list[dict[str, Any]] = []
    seen_keys: set[tuple[Any, ...]] = set()

    for street in STREET_ORDER:
        candidate = next((event for event in ranked if event_street(event) == street), None)
        if candidate is not None:
            selected.append(candidate)
            seen_keys.add(hand_key(candidate))
        if len(selected) >= limit:
            return selected

    for event in ranked:
        if len(selected) >= limit:
            break
        key = hand_key(event)
        if key in seen_keys:
            continue
        selected.append(event)
        seen_keys.add(key)
    return selected


def review_sort_key(event: dict[str, Any]) -> tuple[float, ...]:
    hero_turn = as_dict(event.get("hero_turn"))
    source = as_dict(event.get("source"))
    table = as_dict(event.get("table"))
    hero = as_dict(event.get("hero"))
    action_controls = as_dict(event.get("action_controls"))
    return (
        1.0 if hero_turn.get("is_turn") else 0.0,
        as_float(hero_turn.get("confidence"), 0.0),
        1.0 if action_controls.get("visible") else 0.0,
        1.0 if source.get("hero_cards_locked") else 0.0,
        1.0 if hero.get("gto_position") else 0.0,
        1.0 if table.get("pot_bb") is not None else 0.0,
        as_float(source.get("timestamp_sec"), 0.0),
    )


def build_case(event: dict[str, Any], *, number: int, image_path: Path) -> dict[str, Any]:
    table = as_dict(event.get("table"))
    hero = as_dict(event.get("hero"))
    hero_turn = as_dict(event.get("hero_turn"))
    controls = as_dict(event.get("action_controls"))
    source = as_dict(event.get("source"))
    context = build_preflop_context(event)
    visual_preflop = infer_visual_preflop_hypothesis(event)
    control_assessment = assess_action_controls(event)
    data_flags = assess_card_data(event)
    active_seats = [
        str(seat.get("seat"))
        for seat in list(event.get("seats") or [])
        if str(seat.get("status") or "") == "active_or_showdown"
    ]
    return {
        "number": number,
        "event_index": as_dict(event.get("event")).get("index"),
        "line_number": event.get("_review_line"),
        "timestamp_sec": source.get("timestamp_sec"),
        "image": str(image_path),
        "street": event_street(event),
        "dealer_seat": table.get("dealer_seat"),
        "dealer_position": table.get("dealer_position"),
        "hero_raw_position": hero.get("position"),
        "hero_gto_position": hero.get("gto_position"),
        "hero_preflop_order": hero.get("preflop_action_order"),
        "hero_postflop_order": hero.get("postflop_action_order"),
        "hero_cards": list(hero.get("cards") or []),
        "board": list(table.get("board") or []),
        "pot_bb": table.get("pot_bb"),
        "to_call_bb": table.get("to_call_bb"),
        "visible_bets": normalize_bets(event.get("bets")),
        "active_seats": active_seats,
        "hero_turn": bool(hero_turn.get("is_turn")),
        "hero_turn_confidence": hero_turn.get("confidence"),
        "hero_turn_reason": hero_turn.get("reason"),
        "visible_actions": list(controls.get("actions") or []),
        "call_amount_bb": controls.get("call_amount_bb"),
        "raise_amount_bb": controls.get("raise_amount_bb"),
        "preflop_context": context,
        "visual_preflop_hypothesis": visual_preflop,
        "control_assessment": control_assessment,
        "data_flags": data_flags,
    }


def copy_case_image(event: dict[str, Any], images_dir: Path, number: int) -> Path:
    source_image = Path(str(event["_review_source_image"]))
    event_index = as_dict(event.get("event")).get("index", "unknown")
    timestamp = timestamp_slug(as_dict(event.get("source")).get("timestamp_sec"))
    destination = images_dir / f"case_{number:02d}_event_{event_index}_{timestamp}{source_image.suffix.lower()}"
    shutil.copy2(source_image, destination)
    return destination


def resolve_source_image(event: dict[str, Any], events_path: Path) -> Path | None:
    source = as_dict(event.get("source"))
    sample = as_dict(source.get("card_sample"))
    state_audit = as_dict(source.get("state_audit"))
    # New screen samples carry an expanded context that includes controls below
    # a tight analysis ROI. Prefer it for human state/action review.
    value = (
        state_audit.get("frame")
        or sample.get("screen_context")
        or sample.get("frame")
        or source.get("frame_path")
    )
    if not value:
        return None
    raw = Path(str(value))
    candidates = [raw] if raw.is_absolute() else [Path.cwd() / raw, events_path.parent / raw, events_path.parent / raw.name]
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def render_markdown(events_path: Path, stats: dict[str, int], cases: list[dict[str, Any]]) -> str:
    lines = [
        "# 实盘 CV 状态复盘",
        "",
        f"来源事件流：`{events_path}`",
        "",
        "本报告只写 CV 已观察到的事实。旧版 `gto_advice` 已被忽略；可见下注不是完整行动历史，不能据此断言有人 open、3bet 或该弃牌。",
        "",
        "## 筛选统计",
        "",
        f"- 事件总数：{stats.get('lines', 0)}",
        f"- CV 成功事件：{stats.get('ok_events', 0)}",
        f"- 检测为 Hero 回合：{stats.get('hero_turn_events', 0)}",
        f"- 有原始截图的可复盘候选：{stats.get('eligible_candidates', 0)}",
        f"- 本次选中：{len(cases)}",
        "",
        "## 人工校对规则",
        "",
        "每个案例请确认：1) 是否真轮到 Hero；2) 原始位置；3) 街道；4) 前位完整动作；5) call/raise 按钮金额。确认后才可把场景标成 `RFI`、`vs_open` 或 `vs_3bet`。",
    ]
    for case in cases:
        lines.extend(render_case(case))
    return "\n".join(lines) + "\n"


def render_case(case: dict[str, Any]) -> list[str]:
    context = as_dict(case.get("preflop_context"))
    image_path = Path(str(case["image"]))
    relative_image = Path("images") / image_path.name
    stage = str(case.get("street") or "unknown").upper()
    raw_position = case.get("hero_raw_position") or "-"
    solver_position = case.get("hero_gto_position") or "-"
    hero_turn = "是" if case.get("hero_turn") else "否"
    visible_actions = "/".join(str(item) for item in case.get("visible_actions") or []) or "-"
    bets = format_bets(case.get("visible_bets") or [])
    cards = " ".join(str(card) for card in case.get("hero_cards") or []) or "-"
    board = " ".join(str(card) for card in case.get("board") or []) or "-"
    context_status = preflop_status_text(context)
    visual_preflop = as_dict(case.get("visual_preflop_hypothesis"))
    controls = as_dict(case.get("control_assessment"))
    data_flags = list(case.get("data_flags") or [])
    return [
        "",
        f"## 案例 {case['number']:02d} | {stage} | 事件 #{case.get('event_index')}",
        "",
        f"![案例 {case['number']:02d}]({relative_image.as_posix()})",
        "",
        f"- 时间：{format_seconds(case.get('timestamp_sec'))}；事件流第 {case.get('line_number')} 行",
        f"- 街道：`{case.get('street')}`；庄家：`{case.get('dealer_seat')}` / `{case.get('dealer_position')}`",
        f"- Hero：原始位置 `{raw_position}` -> 策略桶 `{solver_position}`；翻前第 `{case.get('hero_preflop_order')}` 个，翻后第 `{case.get('hero_postflop_order')}` 个",
        f"- 手牌：`{cards}`；公共牌：`{board}`",
        f"- 底池：`{format_bb(case.get('pot_bb'))}`；CV 的 table.to_call：`{format_bb(case.get('to_call_bb'))}`",
        f"- Hero 回合：CV 判为 **{hero_turn}**；依据 `{case.get('hero_turn_reason') or '-'}`；置信度 `{format_number(case.get('hero_turn_confidence'))}`",
        f"- Hero 回合证据评级：**{controls.get('turn_signal') or '-'}**。{controls.get('turn_explanation') or ''}",
        f"- OCR 操作信息：`{visible_actions}`；CALL `{format_bb(case.get('call_amount_bb'))}`；RAISE `{format_bb(case.get('raise_amount_bb'))}`。{controls.get('amount_explanation') or ''}",
        f"- 可见下注：{bets}",
        f"- 仍在牌局的座位：`{', '.join(case.get('active_seats') or []) or '-'}`",
        f"- 单帧翻前观察：**{visual_preflop.get('label') or '-'}**。{visual_preflop.get('explanation') or ''}",
        f"- 翻前场景：**{context_status}**。{preflop_context_explanation(context)}",
        f"- 数据检查：{format_data_flags(data_flags)}",
        "",
        "人工校对：",
        "- [ ] Hero 回合判断正确",
        "- [ ] 位置与街道正确",
        "- [ ] 请补完整翻前动作：`____________________________`",
        "- [ ] 请确认按钮金额：CALL `____ BB`；RAISE TO `____ BB`",
        "- [ ] 正确场景：`RFI / vs_open / vs_3bet / 翻后`；备注：`________________`",
    ]


def preflop_status_text(context: dict[str, Any]) -> str:
    mapping = {
        "unopened": "已确认无人加注",
        "facing_open": "已确认面对 open",
        "facing_3bet": "已确认面对 3bet",
        "limped_pot": "前位 limp，当前策略层未覆盖",
        "four_bet_or_more": "面对 4bet+，当前策略层未覆盖",
        "unknown": "未知",
    }
    return mapping.get(str(context.get("status") or ""), str(context.get("status") or "未知"))


def preflop_context_explanation(context: dict[str, Any]) -> str:
    if context.get("supported"):
        return "可使用明确行动历史进入翻前策略层。"
    needs = ", ".join(str(item) for item in context.get("needs") or [])
    return f"没有完整行动历史，因此不能从单帧下注推断该 raise/call/fold；还需要：`{needs or '行动历史'}`。"


def infer_visual_preflop_hypothesis(event: dict[str, Any]) -> dict[str, str]:
    """State a visual hypothesis without feeding it to the GTO decision API."""

    if event_street(event) != "preflop":
        return {
            "label": "不适用（翻后）",
            "explanation": "翻后单帧只能看到当前下注，无法从此重建翻前完整顺序。",
        }
    hero = as_dict(event.get("hero"))
    hero_order = int_or_none(hero.get("preflop_action_order"))
    seats = [as_dict(item) for item in list(event.get("seats") or [])]
    bb_seat = next((seat for seat in seats if str(seat.get("position") or "") == "BB"), {})
    bb_amount = as_float(bb_seat.get("bet_bb"), 1.0)
    hero_bet = as_float(hero.get("bet_bb"), 0.0)
    earlier = [
        seat
        for seat in seats
        if hero_order is not None
        and int_or_none(seat.get("preflop_action_order")) is not None
        and int_or_none(seat.get("preflop_action_order")) < hero_order
        and as_float(seat.get("bet_bb"), 0.0) > 0
    ]
    earlier_raises = [seat for seat in earlier if as_float(seat.get("bet_bb"), 0.0) > bb_amount * 1.3]
    opponent_raises = [
        seat
        for seat in seats
        if str(seat.get("seat") or "") != str(hero.get("seat") or "")
        and as_float(seat.get("bet_bb"), 0.0) > max(bb_amount * 1.3, hero_bet * 1.15)
    ]
    if hero_bet > bb_amount * 1.3 and opponent_raises:
        actor = opponent_raises[-1]
        return {
            "label": "疑似面对 3bet（仅单帧线索）",
            "explanation": (
                f"Hero 可见投入 {hero_bet:g}BB，另有 {seat_label(actor)} 投入 "
                f"{as_float(actor.get('bet_bb'), 0.0):g}BB；需要回看前后帧确认谁先 raise。"
            ),
        }
    if earlier_raises:
        actor = earlier_raises[-1]
        return {
            "label": "疑似面对 open（仅单帧线索）",
            "explanation": (
                f"Hero 前位 {seat_label(actor)} 可见投入 {as_float(actor.get('bet_bb'), 0.0):g}BB，"
                f"高于 BB 的 {bb_amount:g}BB；可能是 open，也可能是 straddle/残留动画，需人工确认。"
            ),
        }
    return {
        "label": "未见 Hero 前位超过 BB 的投入",
        "explanation": (
            f"当前 BB 可见为 {bb_amount:g}BB；单帧不能区分无人加注、limp 或被遮挡的下注，"
            "因此不能直接当成 RFI。"
        ),
    }


def assess_action_controls(event: dict[str, Any]) -> dict[str, str]:
    table = as_dict(event.get("table"))
    controls = as_dict(event.get("action_controls"))
    hero_turn = as_dict(event.get("hero_turn"))
    regions = [as_dict(region) for region in list(controls.get("red_button_regions") or [])]
    has_large_button = any(
        as_float(region.get("width"), 0.0) >= 90
        and as_float(region.get("height"), 0.0) >= 35
        and as_float(region.get("area"), 0.0) >= 3600
        for region in regions
    )
    if hero_turn.get("is_turn") and has_large_button:
        turn_signal = "强"
        turn_explanation = "检测到足够大的红色按钮区域，截图与 Hero 出牌回合较一致。"
    elif hero_turn.get("is_turn"):
        turn_signal = "弱"
        turn_explanation = "只检测到很小的红色区域，可能是加减/滑条控件；不能仅据此确认轮到 Hero。"
    else:
        turn_signal = "无"
        turn_explanation = "CV 未判定为 Hero 回合；单帧无法识别实际轮到哪一位玩家。"

    call_amount = controls.get("call_amount_bb")
    table_to_call = table.get("to_call_bb")
    if amount_conflicts(call_amount, table_to_call, table.get("pot_bb")):
        amount_explanation = "CALL 数值与 table.to_call/底池明显冲突，疑似读到了其他玩家的记分，不能用于 GTO。"
    elif call_amount is None:
        amount_explanation = "未读到可靠的 CALL 数值。"
    else:
        amount_explanation = "金额没有明显数值冲突，但仍应由按钮文字或前后帧确认。"
    return {
        "turn_signal": turn_signal,
        "turn_explanation": turn_explanation,
        "amount_explanation": amount_explanation,
    }


def assess_card_data(event: dict[str, Any]) -> list[str]:
    hero = as_dict(event.get("hero"))
    table = as_dict(event.get("table"))
    cards = [str(card) for card in list(hero.get("cards") or []) + list(table.get("board") or [])]
    flags: list[str] = []
    duplicates = sorted({card for card in cards if cards.count(card) > 1})
    if duplicates:
        flags.append(f"牌面重复：{', '.join(duplicates)}；当前牌面识别无效，需按原图校对")
    if not duplicates:
        flags.append("手牌与公共牌无重复")
    return flags


def amount_conflicts(call_amount: Any, table_to_call: Any, pot_bb: Any) -> bool:
    if call_amount is None:
        return False
    call_value = as_float(call_amount, 0.0)
    table_value = as_float(table_to_call, 0.0)
    pot_value = as_float(pot_bb, 0.0)
    if table_value > 0 and call_value > max(table_value * 4, table_value + 20):
        return True
    return table_value <= 0 and pot_value > 0 and call_value > pot_value * 3


def seat_label(seat: dict[str, Any]) -> str:
    return f"{seat.get('seat') or '?'} / {seat.get('position') or '?'}"


def format_data_flags(flags: list[str]) -> str:
    return "；".join(flags) if flags else "-"


def event_street(event: dict[str, Any]) -> str:
    return str(as_dict(event.get("table")).get("street") or "").lower()


def hand_key(event: dict[str, Any]) -> tuple[Any, ...]:
    table = as_dict(event.get("table"))
    hero = as_dict(event.get("hero"))
    return (
        event_street(event),
        tuple(hero.get("cards") or []),
        tuple(table.get("board") or []),
        table.get("dealer_seat"),
        table.get("pot_bb"),
    )


def complete_cards(value: Any, *, expected: int) -> bool:
    cards = list(value or [])
    return len(cards) == expected and all(len(str(card)) == 2 and "?" not in str(card) for card in cards)


def complete_board(value: Any, street: str) -> bool:
    expected = {"preflop": 0, "flop": 3, "turn": 4, "river": 5}[street]
    return complete_cards(value, expected=expected)


def normalize_bets(value: Any) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in list(value or []):
        event = as_dict(item)
        rows.append({"seat": event.get("seat") or "?", "amount_bb": event.get("amount_bb")})
    return rows


def format_bets(bets: list[dict[str, Any]]) -> str:
    if not bets:
        return "-"
    return ", ".join(f"`{item.get('seat')}:{format_bb(item.get('amount_bb'))}`" for item in bets)


def format_bb(value: Any) -> str:
    if value is None:
        return "-"
    try:
        return f"{float(value):g} BB"
    except (TypeError, ValueError):
        return str(value)


def format_number(value: Any) -> str:
    if value is None:
        return "-"
    try:
        return f"{float(value):.3f}".rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return str(value)


def format_seconds(value: Any) -> str:
    try:
        return f"{float(value):.3f}s"
    except (TypeError, ValueError):
        return "-"


def timestamp_slug(value: Any) -> str:
    try:
        return f"{float(value):.3f}".replace(".", "p") + "s"
    except (TypeError, ValueError):
        return "unknown"


def as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def as_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def int_or_none(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def format_state_review_summary(payload: dict[str, Any]) -> str:
    if not payload.get("ok"):
        return f"state review failed: {payload.get('error')}"
    stats = as_dict(payload.get("stats"))
    return "\n".join(
        [
            "State review complete.",
            f"Candidates: {stats.get('eligible_candidates', 0)} | selected: {len(payload.get('cases') or [])}",
            f"Report: {payload.get('report_path')}",
            f"Manifest: {payload.get('manifest_path')}",
        ]
    )
